### ISSUE TITLE
Run code only after all process done

### ISSUE THREAD

**Issue by executivoclub** [prampec/IotWebConf#115]
Hello,

First of all, thank you for all the work on this library!

Where I can add the rest of the code, to be executed only when all the Web Config has been executed, and the device is connected to the internet?

I've tried to execute it on the loop, but appears that the code start to be executed and stop the configurator to change the state and connected to the web.

When I remove any of other code, it's goes normally and connect to the internet.

**Comment by prampec** [comment]
You can either use the setWifiConnectionCallback() to specify your custom method to be executed upon wifi connection (this method will be called once, when connection established), or in the loop() you can check the connection status by calling the getState() method. If this method returns IOTWEBCONF_STATE_ONLINE, it means we are connected.
But please not, that either ways, your code must not block the ESP for too long (e.g should finish in milliseconds, or use delay()), so the ESP can maintenance the WiFi communication.
