### ISSUE TITLE
System freeze

### ISSUE THREAD

**Issue by irkami** [prampec/IotWebConf#118]
I observe a short freezing of the system - for processes in the main loop and those in interrupts. I have the impression that this is when the LED is flashing. Anyone had a similar problem?

**Comment by prampec** [comment]
I don't think it has anything to do with blink. On the other hand, there is a yield() call in the doLoop() method. This might perform some ESP internal hooks, that blocks the MCU.
You can however completely disable blinking, please also check that: disableBlink()

**Comment by prampec** [comment]
Please fill free to reopen this issue when you can provide further details in the issue.
