### ISSUE TITLE
POST body possibility?

### ISSUE THREAD

**Issue by sgilissen** [prampec/IotWebConf#122]
Hi, 

First of all, I would like to thank you for building this wonderful library. 
I was wondering if there is a way to get the body of a POST? 
Right now I'm using server.arg("somevariable"), but that's a bit cumbersome, and I'll end up with very long URL's that way. 

If I would be able to just get the body, I can POST a JSON string and parse it. 

Thanks in advance!

Best regards, 

Steve

**Comment by prampec** [comment]
All web functionality is provided by WebServer and it is out of the scope of the IotWebConf.
Please consult WebServer documentation of the Arduino framework of your ESP!
