### ISSUE TITLE
Start With State 3 if wifi is configured.

### ISSUE THREAD

**Issue by AakashKumar21** [prampec/IotWebConf#14]
It takes a lot of time (30 sec approx ) to connect to wifi (state 3) after booting. It should start with state 3.

**Comment by AakashKumar21** [comment]
How to i change time for ap mode at start.

**Comment by prampec** [comment]
Please consult the IotWebConf.h. I recommend to use the setApTimeoutMs() at startup, and later reset it to a valid value. However it would be a nice feature, to skip AP mode at startup and enter only when connection fails. I note that.

**Comment by gusarov** [comment]
I suppose it will work like this if i set ap timout to zero, right?

**Comment by prampec** [comment]
Yes. This is my expectation as well.

**Comment by gusarov** [comment]
Looks like it is not the case
Just faced a situation when it can't connect...
![image](https://user-images.githubusercontent.com/1462777/50801486-fbd48b80-12b2-11e9-8b95-d483656a2df9.png)
And it is not falling back to AP. Well, it is, but looks like 0 timeout forces mode 3 again immediately

**Comment by prampec** [comment]
Right.
1. You need to call the setApTimeoutMs in setup() after init was done. (That you did right.)
2. In the loop, you need to reset the timeout by calling the setApTimeoutMs a second time. But please note, that you need to wait some a second to do this, so that IotWebConf enters state 3.
