### ISSUE TITLE
Add legend to the first separator?

### ISSUE THREAD

**Issue by Klausoleum** [prampec/IotWebConf#144]
Thank you for this wonderful library.

Is there a possibility to add a legend to the first separator?

![InkedScreenshot 2020-09-29 200957_LI](https://user-images.githubusercontent.com/36627883/94605847-f181ce80-0299-11eb-84f8-bdbb7390a445.jpg)

**Comment by jvondrus** [comment]
Hello, I did it by myself by edit library source.
Find "IotWebConf.h" and edit the line:

`const char IOTWEBCONF_HTML_FORM_START[] PROGMEM   = "<form action='' method='post'><fieldset><legend><b>System</b></legend><input type='hidden' name='iotSave' value='true'>";`

**Comment by prampec** [comment]
A completely new approach was introduced with v3.0.0, where you have even more possibilities to customize fieldsets.
