### ISSUE TITLE
Which EEPROM address this Library uses

### ISSUE THREAD

**Issue by AakashKumar21** [prampec/IotWebConf#15]
I want to use EEPROM on my sketch, i need to know what address this library uses.

**Comment by prampec** [comment]
Please consult the IotWebConf.h
Configuration is wrote at the starting address of IOTWEBCONF_CONFIG_START in the "EEPROM". The space used is dependent on the variables you are storing in the configuration, but by default (at least in the current state of the software) 165 bytes are used.
