### ISSUE TITLE
two incorrect characters in System Configuration page v3.0.0

### ISSUE THREAD

**Issue by arvdsar** [prampec/IotWebConf#155]
Hi,
On version 3.0.0 when opening the configuration page there are two characters '> that do not belong there.

This is what the page is showing on top:
'>System configuration

HTML Source:
```
            <input type='hidden' name='iotSave' value='true'>

            '>
            <legend>System configuration</legend>
            <div class=''>
```

**Comment by prampec** [comment]
Thank you for pointing that out. I will address this soon.

**Comment by prampec** [comment]
Fixed.

**Comment by arvdsar** [comment]
Thanks! Can you point me out where you fixed it? I've been searching to see how to do it myself, but couldn't find it.

**Comment by prampec** [comment]
The corporate was in ParameterGroup::renderHtml
```
content = "'>";
```

Where it should have been +=

For me also took some minutes to find it. ;)
