### ISSUE TITLE
Missing / Old files when installing through PlatformIO in VS Code

### ISSUE THREAD

**Issue by bedawi** [prampec/IotWebConf#157]
Hi Balázs Kelemen, many thanks for your work!

Unfortunately when installing your library (v2.3.3) using PlatformIO in VS Code, some files from your repository are missing and old files (like IotWebConfCompatibility.*) are installed. This leads to some problems...

**Comment by prampec** [comment]
Master repository does not contain v2.X.X any more. It is v3.0.0. You can either migrate your code according to the migration guide (recommended), or use branch v2.x.x, thus ```https://github.com/prampec/IotWebConf.git#v2.x.x```

**Comment by prampec** [comment]
(Master repository version does not automatically reflects the published release version. The published release version is still v2.3.3 for the time being.)

**Comment by bedawi** [comment]
Alright, thanks. The issue here is that the examples shown in PlatformIO are already showing code that needs a newer version.
