### ISSUE TITLE
git tag for 3.0.0 is missing

### ISSUE THREAD

**Issue by ThomasWaldmann** [prampec/IotWebConf#160]
also, the github release.

**Comment by prampec** [comment]
v3.0.0 is not release just jet. Let's say we are in the beta stage now. Actual release will be published in a week or two.

**Comment by ThomasWaldmann** [comment]
well, platformio is already installing it if one does not have `IotWebConf@<3.0.0` (and breaking builds due to the incompatible changes).

so, that is practically released i would say. :-)

**Comment by prampec** [comment]
Yes. But you certainly have a very effective tool to revert to 2.x.x version in case of any trouble. For the ones are using Arduino, it is not easy.
