### ISSUE TITLE
UTF-8 config

### ISSUE THREAD

**Issue by coelner** [prampec/IotWebConf#163]
https://github.com/prampec/IotWebConf/blob/01422130a3f85845a9a225fc25d8699616152ee6/examples/IotWebConf10CustomHtml/IotWebConf10CustomHtml.ino#L117

This works online for the root Handle, the config page does not serve UTF-8, which results in broken emoji render.
![Screenshot_20210106-124530](https://user-images.githubusercontent.com/16364254/103767020-1f587b00-5020-11eb-9464-bbc3904f06cf.png)

**Comment by prampec** [comment]
Added ```charset=UTF-8``` to the config page. Please verify against latest GIT version!
