### ISSUE TITLE
How to use library on MEGA+WiFi R3 ATmega2560+ESP8266

### ISSUE THREAD

**Issue by ivan-shaban** [prampec/IotWebConf#168]
Hello, i'm using board MEGA+WiFi R3 ATmega2560+ESP8266. When i'm trying to upload `IotWebConf01Minimal.ino` sketch to ATmega2560, i got an error:
```
...\Documents\Arduino\libraries\IotWebConf\src/IotWebConf.h:26:10: fatal error: DNSServer.h: No such file or directory
 #include <DNSServer.h> // -- For captive portal
          ^~~~~~~~~~~~~
compilation terminated.
```
When i upload sketch to esp directly, everything works fine. 

Question: is it possible to use that library with ATmega2560? ATmega2560 communicates with esp by serial3 (afaik).

**Comment by prampec** [comment]
This library is not intended to be used on ATmega2560. However IotWebConf is also just slightly depends on ESP. Further more, ESP32 wants to be as generic as possible, so IotWebConf might also be adopted to boards, that supports wifi hooks and webserver.
With v3.0.0 IotWebConf introduces WebServerWrapper, with this you can provide support for any extraordinary webservice implementation.
(On the other hand, it is not very likely, that boards line ATmega2560 can provide enough program memory to be capable to do all wifi-internet-web things.)
