### ISSUE TITLE
Do not print passwords by default

### ISSUE THREAD

**Issue by gusarov** [prampec/IotWebConf#17]
Please, disable passwords prints by default. It can be enabled via additional #define if needed
This prevents e.g. online demos and conference calls... Even showing to the friends over the table doesn't looks safe. Needless to say somebody smart enough can use a portable serial analyzer to still this from already working iot.

I know there is a #define for disabling all prints, but I still would like to have the rest of them.
You did a great security considerations forcing people to set the passwords to device, but this prints reduces security a lot.

**Comment by prampec** [comment]
Fixed. Will be released with version v2.1.0
