### ISSUE TITLE
Example IotWebConf04UpdateServer showing error

### ISSUE THREAD

**Issue by worthapenny** [prampec/IotWebConf#173]
Hi there,

First of all thanks for sharing the work!

I copied the Example (UpdateServer) into PlatformIO and it is showing some error:

![image](https://user-images.githubusercontent.com/34549180/110258280-0b1cf580-7f5f-11eb-9a2c-8438cf6f0ebc.png)

![image](https://user-images.githubusercontent.com/34549180/110258317-3d2e5780-7f5f-11eb-9729-694d3a703be6.png)

Error causing lines (which is hard to see in the screenshot):
```CPP
  // -- Define how to handle updateServer calls.
  iotWebConf.setupUpdateServer(
    [](const char* updatePath) { httpUpdater.setup(&server, updatePath); },
    [](const char* userName, char* password) { httpUpdater.updateCredentials(userName, password); });
```

My limited knowledge is not helping me to troubleshoot this error. Hence, any suggestion would be appreciated.

**Comment by prampec** [comment]
You have some mix-up in your library/examples version. Please make sure you are using IotWebConf 3.0.0-pre.X version (or later) on both library and examples side.

**Comment by prampec** [comment]
Please update to IotWebConf 3.0.1 as there was some mix-up with naming 3.0.0*
