### ISSUE TITLE
atoi returns wrong stringParamValue in an array

### ISSUE THREAD

**Issue by 1TekPro** [prampec/IotWebConf#20]
@prampec  If I erase the flash, I get one correct value. But if I set the same value in the config portal, I get strange numbers like these:
Timer0 is 1073422788 seconds.
Timer1 is 1073422788 seconds.
Timer2 is 1073422788 seconds.
Timer3 is 1073422788 seconds.

 `#include <stdio.h>
#include <string.h>
#include <IotWebConf.h>

#define STRING_LEN 128
#define NUMBER_LEN 32
#define CONFIG_VERSION "0.8.2"
#define CONFIG_PIN 2
#define STATUS_PIN LED_BUILTIN

#define maxnumberOfTimers 30

const char thingName[] = "testThing";
const char wifiInitialApPassword[] = "smrtTHNG8266";

char stringParamValue[STRING_LEN];
char intParamValue[NUMBER_LEN];
char floatParamValue[NUMBER_LEN];

void configSaved();
boolean formValidator();

DNSServer dnsServer;
WebServer server(80);

IotWebConf iotWebConf(thingName, &dnsServer, &server, wifiInitialApPassword, CONFIG_VERSION);
IotWebConfParameter stringParam = IotWebConfParameter("Relay Timer Queue (on/off times in seconds separated by commas [30 MAX])", "stringParam", stringParamValue, STRING_LEN);

void setup() {
  Serial.begin(115200);
  Serial.println();
  Serial.println("Starting up...");

  iotWebConf.setStatusPin(STATUS_PIN);
  iotWebConf.setConfigPin(CONFIG_PIN);
  iotWebConf.addParameter(&stringParam);
  iotWebConf.setConfigSavedCallback(&configSaved);
  iotWebConf.setFormValidator(&formValidator);
  iotWebConf.getApTimeoutParameter()->visible = true;

  iotWebConf.init();

  server.on("/", handleRoot);
  server.on("/reboot", handleReboot);
  server.on("/config", []{ iotWebConf.handleConfig(); });
  server.onNotFound([](){ iotWebConf.handleNotFound(); });
  
  checktimers();
  
  Serial.println("Ready.");
}

int checktimers(void) {
  char str[STRING_LEN];
  memcpy(str,stringParamValue,sizeof(stringParamValue));
    int numberOfEntries = 0;
    char *currentEntry = strtok (str, ",");
    int entries[maxnumberOfTimers];

    while (currentEntry != NULL) {
      entries[numberOfEntries++] = atoi(currentEntry);
      currentEntry = strtok (NULL, ",");
    }
      for (int i = 0; i < numberOfEntries; i++) {
        Serial.println(i);
        printf("Timer%d is %d seconds.\n", i,  entries[numberOfEntries]);
      }
    return 0;
}

void handleRoot() {
  if (iotWebConf.handleCaptivePortal()) {
    // -- Captive portal request was already served.
    return;
  }
  String s = "<!DOCTYPE html><html lang=\"en\"><head><meta name=\"viewport\" content=\"width=device-width, initial-scale=1, user-scalable=no\"/>";
  s += "<title>WST-MicroCore Parameters</title></head><body>WST-MicroCore";
  s += "<ul>";
  s += "<li>Current Timer Queue: <br>";
  s += stringParamValue;
  s += "</ul>";
  s += "<a href='config'>Configuration Page</a><br>";
  s += "<a href='reboot'>Reboot Controller</a>";
  s += "</body></html>\n";

  server.send(200, "text/html", s);
}

void handleReboot() {                   // meta refresh needs work
  if (iotWebConf.handleCaptivePortal()) {
    // -- Captive portal request were already served.
    return;
  }
  String s = "<html xmlns=\"http://www.w3.org/1999/xhtml\"><head><meta http-equiv=\"refresh\" content=\"10000;URL=/\" />";
  s += "<title>Rebooting...</title></head><body>Rebooting...</body></html>\n";
  
  server.send(200, "text/html", s);
  delay(500);
  ESP.restart();
}

void configSaved() {
  Serial.println("Configuration was updated.");
}

boolean formValidator() {
  Serial.println("Validating form.");
  boolean valid = true;

  int l = server.arg(stringParam.getId()).length();
  if (l < 3) {
    stringParam.errorMessage = "Please provide at least 2 timers (example: 30,15)";
    valid = false;
  }
  return valid;
}

void loop() {
  // -- doLoop should be called as frequently as possible.
  iotWebConf.doLoop();
}`

**Comment by prampec** [comment]
Sorry, I don't see the connection between this problem and IotWebConf. Further more I'm not an experienced C programmer any more, so I cannot help with strtok behavior. I recommend you to write a lot of debug info to the console to sort out the problem.
