### ISSUE TITLE
REQUEST set Max MQTT count attempt connection function

### ISSUE THREAD

**Issue by joko2020** [prampec/IotWebConf#209]
Is ther function to set Max MQTT attempt connection?, if MAX MQTT count attempt  = true , then trigering goOffline() function until board reset or on demand button is pressed.

this Idea came from example `IotWebConf16OfflineMode.ino`

thanks

**Comment by prampec** [comment]
I'm not completely sure if this question has anything to do with IotWebConf.
Yes, you can certainly count your failed connections against your MQTT server, and yes there is a function on IotWebConf for entering offline mode. IotWebConf does not manage MQTT connection, it maganes the WiFi only.
