### ISSUE TITLE
load JsonConfig does not work with checkbox

### ISSUE THREAD

**Issue by MatMat81** [prampec/IotWebConf#217]
tested with parameters:  '"true"', "true", "1", "'1'", "selected", "checked"
 ....
none switches the checkbox to true.
All other parameters can be set ...
....
         "iwcCustom": {
             "c_factor": {
                 "flParam": "55.25",
                 "checkParam2": true,
                 "checkParam": "true",
                 "chooseParam": "red"
             },
             "intFac": {
                 "inParam": "20"
             }

**Comment by MatMat81** [comment]
i have found the solution:
"checkParam": "selected" 
is the key word for setting the checkboxes...

completed...

**Comment by prampec** [comment]
Yes. JsonConfig will be much nicer if TypedParameter approach can overtake regular parameters. In that case parsing should be done type based, meaning float parameters will accept numbers instead of string on Json.

**Comment by MatMat81** [comment]
can you add the solution to the config.json example No.17 so that other people have no problem?

**Comment by prampec** [comment]
I have added this note to the README of the example, because it should also be documented how a not selected value look like.
