### ISSUE TITLE
mDNS and connecting to hostname.local , I cant seem to get it to work

### ISSUE THREAD

**Issue by jessel92** [prampec/IotWebConf#22]
Am I the only one having this issue?

If so can someone walk me through how to set this up.
Its automatically setup as my "thingname" right?
Or is there another step I need to take to init it.

Sorry if this is a stupid question! I'm far from an expert.
Everything else is working great though!

**Comment by prampec** [comment]
Unfortunately I'm not an expert of the network layer of ESP8266/ESP32 either. What I can say, is that I was trying to follow the regular steps for mDNS, but there might be some tricks, because I can confirm that this part is not 100% reliable. So any feedback/hint here is very welcomed.
