### ISSUE TITLE
Unreachable code inside loadConfig() function

### ISSUE THREAD

**Issue by hieunvce** [prampec/IotWebConf#226]
File: IotWebConf.cpp
Line: 173
Function: loadConfig

As I know, this code:

```C
EEPROM.end();
```
is unreachable.

Is it OK? 
I wonder whether it cause buggy behavior?

Thank you so much!
![Screenshot from 2021-10-19 22-18-17](https://user-images.githubusercontent.com/29145542/137942369-a23127cb-8525-484f-a96b-6820f3102458.png)

**Comment by prampec** [comment]
You are right. This need to be fixed ASAP.

**Comment by prampec** [comment]
Fixed in v3.2.1
