### ISSUE TITLE
Error in AP mode

### ISSUE THREAD

**Issue by b1gmans** [prampec/IotWebConf#23]
Everything was working fine, but now I have this error, when I load up a new module or if I force an existing one back into Ap mode by connecting to it from my phone. 

E (27188) event: mismatch or invalid event, id=63
E (27189) event: default event handler failed!

It seems to be something to do with the ESP32 libraries themselves, but I just cannot get any of my projects that I have build with the IotWebConf to work anymore if the device is in AP mode?

Anyone got a work around?

**Comment by gyromike** [comment]
I had to let it erase all content when doing the flash update

**Comment by gyromike** [comment]
only works the first time.  after that it blocks and waits

**Comment by gyromike** [comment]
looks like there was a arduino core change that is causing file problems

**Comment by prampec** [comment]
Can you please provide some reference some if you found any connection with other issues?!

**Comment by gyromike** [comment]
Still not sure what causes the problem.  I am getting data corruption in my files.  I write a value and then read it back to find that it has changed without me writing to the file again.  It does not look like I can cause the problem with a smaller sketch.  Not sure what to try next.
