### ISSUE TITLE
Can't connect after reset with custom param

### ISSUE THREAD

**Issue by davpirelli** [prampec/IotWebConf#239]
Hi, i've successfully setup on my NodeMCU this library and the "basic" example works like a charm, even after power off the device.

When i use the "Custom param" (or any other example) the board can't connect back to my WiFi and start in the AP Mode.

Any suggestion?

**Comment by EricDuminil** [comment]
Hi!

I just tried `IotWebConf03CustomParameters.ino` on ESP8266, without changing anything.
The ESP does start in AP mode, and mentions in the console that:

```
AP password was not set in configuration
State changing from: 0 to 1
Setting up AP: testThing
With default password: <hidden>
AP IP address: 192.168.4.1
AP password was not set.
WiFi SSID was not set.
Will stay in AP mode.
```

If you only set SSID+Wifi password in the configuration page, you'll get a message that:

> Configuration saved. You must change the default AP password to continue. 

If you set the AP password to at least 8 characters and apply, the ESP will try to connect to WiFi, and won't start in AP automatically again.
You'll see the IP address in the console, and will be able to connect to the webpage with 'admin' user and the AP password you've chosen.
