### ISSUE TITLE
Support async web server (ESPAsyncWebServer)

### ISSUE THREAD

**Issue by jeppo7712** [prampec/IotWebConf#24]
Are there any plans to make this work with an async web server?

**Comment by prampec** [comment]
Please explain what you mean on "async web server"!

**Comment by jeppo77** [comment]
sorry maybe I should have been more clear. Please have a look here 
https://github.com/me-no-dev/ESPAsyncWebServer
There is no "handleClient" in the loop. Server connections are handled asynchronously (faster, more connections...)

**Comment by prampec** [comment]
Thank you for the idea. This is certainly something that worth considering. At a first look my concern is, that this way we would introduce two third party library dependency. On the other hand, I see the benefits. A solution could be to introduce a fork with async web server.
I keep this thread open.

**Comment by gibo77** [comment]
I will try this one.
https://github.com/alanswx/ESPAsyncWiFiManager

**Comment by prampec** [comment]
Unfortunatelly ESPAsyncWebServer and WebServer does not share any common features. So it is not obvoius how handle both of them in the same code. So we stuck with the option of forking IotWebConf with using the ESPAsyncWebServer.

**Comment by prampec** [comment]
As mentioned in #133, IotWebConf v3.0.0 introduces some nice features to implement this option, however I lack the resources to do it myself. Help is welcomed!
