### ISSUE TITLE
Conflict between IotWebConf library and getEvent function from Adafruit libraries

### ISSUE THREAD

**Issue by jgarcia-atg** [prampec/IotWebConf#240]
Hello.

I have detected a conflict between this IotWebConf library and, in my case, Adafruit's AHT20 sensor code needed for reading its values.
I was using example "IotWebConf06MqttApp" as a refference and I wanted to also read data from this sensor. Code for this sensor is also extracted from its example "adafruit_aht_test", and it is the following one:

```
#include <Adafruit_AHTX0.h>

Adafruit_AHTX0 aht;

void setup() {
  Serial.begin(115200);
  Serial.println("Adafruit AHT10/AHT20 demo!");

  if (! aht.begin()) {
    Serial.println("Could not find AHT? Check wiring");
    while (1) delay(10);
  }
  Serial.println("AHT10 or AHT20 found");
}

void loop() {
  sensors_event_t humidity, temp;
  aht.getEvent(&humidity, &temp);// populate temp and humidity objects with fresh data
  Serial.print("Temperature: "); Serial.print(temp.temperature); Serial.println(" degrees C");
  Serial.print("Humidity: "); Serial.print(humidity.relative_humidity); Serial.println("% rH");

  delay(500);
}
```

I have made some experiments and it seems that function `aht.begin()` and `aht.getEvent()` make that my ESP12f do not connect to the WiFi that I have specified on its AP page.

I can use `sensors_event_t humidity, temp` but getEvent or begin make this device unable to connect to te WiFi, because the Watchdog acts and reboots the ESP.

Has anyone else see this error?
Thank you in advance.

**Comment by prampec** [comment]
As far as I see aht.getEvent() uses delays while receiving results. It is overall not a good practice to use delays. Instead callbacks should have been utilized here.
I recommend you to avoid aht.getEvent().
