### ISSUE TITLE
example iotweb06 Topic must not have / at the beginning

### ISSUE THREAD

**Issue by toedtnissen** [prampec/IotWebConf#246]
mqttClient.publish("test/status", pinState == LOW ? "ON" : "OFF");
 

  mqttClient.subscribe("test/action");

**Comment by prampec** [comment]
You are right, on that leading slash is not required in topic names. But it does not harm either.

I personally use it that way, e.g.:
<reserved>/<location>/<device_type>/<message_kind>/<device_id>

Where "reserved" is currently empty. I will still correct it according to your suggestion not to mislead others.
