### ISSUE TITLE
Won't Connect to Network Sparkfun ESP32 S2 Thing Plus

### ISSUE THREAD

**Issue by AardvarkMan** [prampec/IotWebConf#266]
Using a known good setup that works on an Adafruit ESP32 Feather. I attempt to run the same code on the SparkFun ESP32 S2 WROOM Thing Plus device and it runs through the setup loop, allows a remote connection for configuration, but I get the "Giving Up" timeout when attempting to connect to the configured WIFI.

I've enabled the debugging to see the entered passwords, and everything appears correct, and the same code on a different ESP32 device works as expected.

I see the same behavior with the supplied example programs.

Using the Arduino IDE supplied WIFI examples, I can connect to the network using a static configuration.

Is there anything I can try or information I can provide for this issue? Is this an issue with the S2 devices?

**Comment by BrainHunter** [comment]
Hi there, 

I have the same problem with a lolin s2 mini board. 
initial AP works fine but then connecting to my wifi is not possible.
what i also see is: when the board switches back to AP after the timeout it is not visible to any device. 
seems that reconfiguring from initial Ap to STA back to AP breaks wifi.

also tried some arduino wifi examples: No problem connecting to my wifi there.

**Comment by BrainHunter** [comment]
> I have the same problem with a lolin s2 mini board. initial AP works fine but then connecting to my wifi is not possible. what i also see is: when the board switches back to AP after the timeout it is not visible to any device. seems that reconfiguring from initial Ap to STA back to AP breaks wifi.

update from my side: 
i just updated my esp32 platform package (now V5.2.0) within platformio and now it seems to work!

**Comment by AardvarkMan** [comment]
I built the code in PlatformIO with the 6.1.0 platform package and it is working great. I guess it is something in the Arduino compile process.

I'm not sure how to fix this for the Arduino IDE, but PlatformIO is a working solution.
