### ISSUE TITLE
Password parameter visibility

### ISSUE THREAD

**Issue by pfeno** [prampec/IotWebConf#32]
Is it possible to add the functionality, like in Android (as picture below) and some others OS, to have an icon to make visible the password?

![password eye](https://user-images.githubusercontent.com/9256659/54518366-5a2d8280-4964-11e9-92c2-79a6b5f14e0f.png)

**Comment by prampec** [comment]
Currently IotWebConf config visualization is based on pure HTML without any additional libraries to keep the solution as simple as possible and keep the footage low. As far as I know currently HTML doesn't support the feature you want natively.
The solution could be to add the possibility for including external HTML libraries, but IotWebConf does not support that either. So let's keep this issue open, to fix this one.

**Comment by prampec** [comment]
Done in v2.3.0
Please check example 10, that implements exactly this feature.
