### ISSUE TITLE
Internal parameters (setter)

### ISSUE THREAD

**Issue by pfeno** [prampec/IotWebConf#33]
Is it possible to have a sample or setters for modify the following internal parameters?
Why? After the first boot and initial configuration, I have a touchscreen display and I want to modify the value directly from the display. 
Perhaps i need to reset entirely the previous configuration.

Also,  how to access others parameters like MQTT id and pasword? What am I supposed to do? Reread the EEPROM from my stuff?

```
/**
     * Get internal parameters, for manual handling.
     * Normally you don't need to access these parameters directly.
     * Note, that changing valueBuffer of these parameters should be followed by configSave()!
     */
    IotWebConfParameter* getThingNameParameter() { return &this->_thingNameParameter; };
    IotWebConfParameter* getApPasswordParameter() { return &this->_apPasswordParameter; };
    IotWebConfParameter* getWifiSsidParameter() { return &this->_wifiSsidParameter; };
    IotWebConfParameter* getWifiPasswordParameter() { return &this->_wifiPasswordParameter; };
    IotWebConfParameter* getApTimeoutParameter() { return &this->_apTimeoutParameter; };
```

**Comment by prampec** [comment]
No, no!
First of all, you have full control on your own parameters (e.g. MQTT password).
The getter here returns with the pointer of the whole internal IotWebConfParameter. So again, you have full access on these parameters as well.
Please note the comment "changing valueBuffer of these parameters should be followed by configSave()". So you can change the valueBuffer of any internal or external parameter, but you must call the configSave() method to persist these changes.
