### ISSUE TITLE
Setting Hostname

### ISSUE THREAD

**Issue by electrontube** [prampec/IotWebConf#40]
Is there a way to set the hostname?
Currently the device appears as: ESP_nnnnnn (when connected)
It would be nice to have an option to set hostName = thingName
or even better to have an extra field on the config page to set the hostname individually.

**Comment by prampec** [comment]
IotWebConf tries to set the hostname to the name defined in the Web configuration page. However I also have faced with problems where it was not done. Not sure why.

**Comment by electrontube** [comment]
Thanks for the response, which leads to the next question:
Will there be any further development soon?

**Comment by prampec** [comment]
Regarding to this particular problem (or for any other problem), what I can say is, that when one can form a detailed reproducible report of an obvious error, than I will do my best correct that error.

Further more there is a "Feature request" section in the README, with the ideas I might want to address sooner or later.

But any contribution is very welcomed.

**Comment by electrontube** [comment]
Thanks again for your response!
That sounds a bit like: "be patient, it will take quite a while"

**Comment by prampec** [comment]
What can I say? :) You see it right.
The library is quite stable now, I have spent a lot of effort to achieve this level. Now there is nothing that hurries me.

**Comment by all-solutions** [comment]
Try 
_void setup () {
[...]
WiFi.hostname(iotWebConf.getThingName());
[...]
}_

**Comment by electrontube** [comment]
@all-solutions 
Thanks for your response, 

> 
> ```
> void setup () {
> [...]
> WiFi.hostname(iotWebConf.getThingName());
> [...]
> }
> ```

Did not make any difference, HostName still is ESP_nnnnnn

Any other ideas?

**Comment by electrontube** [comment]
> 
> ```
> void setup () {
> [...]
> >  WiFi.begin();
> [...]
> }
> ```

seems to do the trick... 
can anyone confirm this?
