### ISSUE TITLE
store numbers as numbers

### ISSUE THREAD

**Issue by smartinick** [prampec/IotWebConf#43]
Very interesting project, Thanks for providing the code!

except for the missing espasyncwebserver (issue #24), i'm wondering about one more thing:

e.g. in example IotWebConf03CustomParameters.ino, there's a Int, limited with min/max from 1-100, and it's stored in RAM and Eeprom as a 32byte string.

in that case it could be done using one byte - type uint8.

is there a reason you went the char[32] route?

except for the waste of resources, it would be easier is the user-code could access the value of the parameter in correct type (so no need to add another uint8_t and convert from char[] to uint8_t...

it would be very great to have support for unsigned/signed int 8/16/32 as well as float.

what do you think?

**Comment by prampec** [comment]
With v3.0.0 typed parameters are introduced to address this issue. It is not officially supported, but seams to be stable. Might be subject of change. (E.g. some constructors are likely to be changed.)
