### ISSUE TITLE
Disconnection Debugging

### ISSUE THREAD

**Issue by chinswain** [prampec/IotWebConf#46]
Could you give an example of handling connection failures? I don't want the library falling back to AP if there's a connection problem, I want to keep trying without blocking and log this.

I see setWifiConnectionFailedHandler, do you have an example?

**Comment by prampec** [comment]
This is a very advanced mode, and I do not plan to provide examples for that. Sorry. Maybe some kind of Pastebin sample instead. But I cannot promise anything now.
