### ISSUE TITLE
Switch off and on the wifi

### ISSUE THREAD

**Issue by gergokoos** [prampec/IotWebConf#5]
Hello,

probably it's a weird thing to do, but in my project I don't want to use the wifi all time long, just for some time to set the time up and change the settings.

Is there any way to switch off the wifi (without connecting to the local network or creating an ap) and then switch it on again?

Thanks!

**Comment by prampec** [comment]
IotWebConf should be flexible for developers, an option like this can be certainly implemented.

**Comment by 1TekPro** [comment]
This should be done at sketch level not with IotWebConf.

**Comment by prampec** [comment]
A new skipApStartup mode was introduced. So WiFi will be stayed on as long as it is available. However you still cannot force the module from code to jump into AP mode.

**Comment by 1TekPro** [comment]
Sure you can. Why don't you think it can be done?

**Comment by prampec** [comment]
No, no. I meant the IotWebConf does not yet provide a method to jump into AP mode (IOTWEBCONF_STATE_AP_MODE).

**Comment by hizzawaseem** [comment]
Hi,
I am relatively new at firmware development. In my project I want the device to start up in Station mode (instead of AP Mode) if device startup configurations are present in EEPROM. At the current instance the device always starts up in AP mode.
I tried to forcefully switch the device to station mode using these commands but it didn't work. 
  WiFi.softAPdisconnect(true);
  WiFi.mode(WIFI_STA);
Thanks!

**Comment by pfeno** [comment]
Do you think it's difficult to implement in a futur release ?

**Comment by prampec** [comment]
This issue is still open, and I suppose to provide a solution for that. The only thins is that is does not have high priority. :(

**Comment by dopyoman** [comment]
Ya I  was looking for a way to do this with the library. It makes me sad that it's not possible.

**Comment by prampec** [comment]
This issue is still on the TODO list. Also requested by others #149.

**Comment by prampec** [comment]
I have provided to you an OffLine mode. Please check example IotWebConf16OffLineMode.
Solution will be available from v3.1.0
