### ISSUE TITLE
add svg graphics

### ISSUE THREAD

**Issue by fabltd** [prampec/IotWebConf#54]
Hi 

Any pointers on how to add an SVG to the config page?

**Comment by prampec** [comment]
There are some request regarding extending the HTML capabilities of the config page. So this will be the next on my TODO list.

**Comment by fabltd** [comment]
Thanks

Is there an ETA?

Regards,
Jeremy

On 1 Jul 2019, at 21:41, Balázs Kelemen <notifications@github.com> wrote:

There are some request regarding extending the HTML capabilities of the
config page. So this will be the next on my TODO list.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/prampec/IotWebConf/issues/54?email_source=notifications&email_token=ABGCGRSVXLQHFJEMWLGL6C3P5JTY5A5CNFSM4H4VUYW2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODY7JKLY#issuecomment-507417903>,
or mute the thread

**Comment by prampec** [comment]
it is done by now. I'm need to test things tho. E.g. by provide an example

**Comment by fabltd** [comment]
Hi

Is there an email I can send you a file to ?

J

On 4 Jul 2019, at 10:30, Balázs Kelemen <notifications@github.com> wrote:

it is done by now. I'm need to test things tho. E.g. by provide an example

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/prampec/IotWebConf/issues/54?email_source=notifications&email_token=ABGCGRTBKVTYBADKESCGEY3P5W7KHA5CNFSM4H4VUYW2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODZG4IMQ#issuecomment-508412978>,
or mute the thread

**Comment by prampec** [comment]
It is not ideal to include files in examples, as it needs to be uploaded to SPIFFS and used from that location. Makes the example very complicated and eventually impossible to run for beginners. Instead I'm thinking about using an inline PNG image as an example.

**Comment by fabltd** [comment]
Hi

The SVG could be included in a header file ?

On 4 Jul 2019, at 15:16, Balázs Kelemen <notifications@github.com> wrote:

It is not ideal to include files in examples, as it needs to be uploaded to
SPIFFS and used from that location. Makes the example very complicated and
eventually impossible to run for beginners. Instead I'm thinking about
using an inline PNG image as an example.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/prampec/IotWebConf/issues/54?email_source=notifications&email_token=ABGCGRRA2DA5MXJ4AXQVPIDP5YA4DA5CNFSM4H4VUYW2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODZHRA6Y#issuecomment-508498043>,
or mute the thread

**Comment by prampec** [comment]
What do you mean by that? What I will do is to provide options to customize the generated HTML code. I will not give advises on that how to manipulate HTML code. There are way to many online resources for that.

**Comment by fabltd** [comment]
Can i test this now?

**Comment by prampec** [comment]
The code and the example is ready on my computer, but unfortunately I have run into hardware/driver issues, after the first test: my computer does not recognize my ESP8266 any more. (I need to find another computer.)

**Comment by prampec** [comment]
Done in v2.3.0
