### ISSUE TITLE
Change of standard labels and parameters

### ISSUE THREAD

**Issue by ifamed** [prampec/IotWebConf#55]
Hi, @prampec .
How can I change the default labels ("**Thing name**", "**AP password**", "**WiFi SSID**", "**WiFi password**", "**Startup delay (seconds)**") for these parameters?
I will be grateful for the answer or for the implementation of this.

`this->_thingNameParameter = IotWebConfParameter("Thing name", "iwcThingName", this->_thingName, IOTWEBCONF_WORD_LEN);`

`this->_apPasswordParameter = IotWebConfParameter("AP password", "iwcApPassword", this->_apPassword, IOTWEBCONF_WORD_LEN, "password");`

`this->_wifiSsidParameter = IotWebConfParameter("WiFi SSID", "iwcWifiSsid", this->_wifiSsid, IOTWEBCONF_WORD_LEN);`

`this->_wifiPasswordParameter = IotWebConfParameter("WiFi password", "iwcWifiPassword", this->_wifiPassword, IOTWEBCONF_WORD_LEN, "password");`

`this->_apTimeoutParameter = IotWebConfParameter("Startup delay (seconds)", "iwcApTimeout", this->_apTimeoutStr, IOTWEBCONF_WORD_LEN, "number", NULL, NULL, "min='1' max='600'", false);`

**Comment by prampec** [comment]
This will be a kind of under-the-hood trip.

So first of all, you need to access those variables. You can do it by e.g. `IotWebConfParameter* thingNameParam = iotWebConf.getThingNameParameter();`

With this you are already able to access the label, e.g.: `Serial.println(thingNameParam->label);`

Now, to modify the value of this value, you need to redirect the existing pointer to a new location. E.g. `thingNameParam->label = "Alias for this device"`;

Please note, that the code above not tested. And I just hope, that the "new location" is constant indeed, so it will stay in memory after the actual scope ends.
