### ISSUE TITLE
Config doesnt accept username and password after wifi config finished

### ISSUE THREAD

**Issue by dboon1978** [prampec/IotWebConf#56]
Once initial wifi setup is complete I'm unable to connect to config as the username and password I entered are not accepted.

UPDATE:  figured out the username is 'admin'.  Perhaps I missed it in the documentation

**Comment by Geraldo-Neto** [comment]
What is the password? Can't find it.

**Comment by prampec** [comment]
You might want to turn on all debugging, and check the serial console for the passwords compared.

**Comment by prampec** [comment]
The web-access login when connected to the WiFi network is:
User name: admin
Password: <configured AP password>

A proper user-documentation is sill pending tho.
