### ISSUE TITLE
PW's displayed in clear text in Serial monitor

### ISSUE THREAD

**Issue by syrinxtech** [prampec/IotWebConf#57]
First of all.....thanks for your work on this library!  While I have made a lot of changes and modifications for my use, you have saved me a lot of time and effort.

I started at version 2.1.0 and am currently using 2.2.1.  My question is in regards to the WIFI passwords being displayed in clear text when Serial logging.  In `IotWebConf::configSave()`, unless you `#define IOTWEBCONF_DEBUG_PWD_TO_SERIAL`, the WIFI passwords are shown as "`<hidden>`".  However, when you change the WIFI password(s) and save the configuration parameters at "`/config`" and `IotWebConf::readParamValue()` runs, the WIFI passwords are shown in clear text.  

Is there a way to hide them in the second case?

Thx

**Comment by prampec** [comment]
Version 3.0.0 fixes all similar problems.
