### ISSUE TITLE
Reset a IotWebConfParameter to default?

### ISSUE THREAD

**Issue by syrinxtech** [prampec/IotWebConf#59]
Is there a way to reset a parameter after it has been configured through the web interface?

I tried the web interface to a separate database containing nodes with a custom struct.  When I delete the nodes in the database, I would like to go back to the web side and reset the values to their defaults.  Otherwise, when a new parameter is created, it inherits the settings saved for the previous parameter.

It would be especially nice if it was a public function so it could be called from other source files.

**Comment by prampec** [comment]
Check #176, but basically you can e.g. use:
iotWebConf.getSystemParameterGroup()->applyDefaultValue();

Will be enabled with version v3.0.2
