### ISSUE TITLE
Most of times not shows the configuration page

### ISSUE THREAD

**Issue by alexjalser94** [prampec/IotWebConf#64]
Hi! I´m using this in ESP32, but I have an issue that I can´t resolve, the only way to view the configuration page is when I connect to the AP and immediately reload a page in the browser with 192.168.4.1/config, but if only I connect and wait till this page it doesn't show...
I don't know what can occur, but I only can run it correctly if do the trick that I mentioned previously, can you help me? Maybe if we can force the configuration page by the .ccp can resolve this, but I have no idea where I have to touch...

This one I when I startup normally and I connect to the AP, but it stuck as you can see

![Anotación 2019-09-02 151224](https://user-images.githubusercontent.com/53453109/64117365-4f8d6b00-cd95-11e9-8c18-51fbfa6f0c49.png)

And this one (showing that is runs) is when I am reloading in the browser during the connection to the AP, and changing some values

![Anotación 2019-09-02 151254](https://user-images.githubusercontent.com/53453109/64117469-911e1600-cd95-11e9-9488-9cbe628692d3.png)

Please help me to solve it! Thanks :)

**Comment by balajtii** [comment]
Hi! Same here. After I stuck with error repair, I opened a new project and copy/paste my old code block by block (logical blocks eg connection management, mqtt connection, mqtt topic name generation...etc) and testing wich block give the error and nothing, my new file works great with almost the same code. I don't get the solution.

**Comment by prampec** [comment]
Sorry I cannot provide any hints for you on that, expect for encourage you to experiment using different ESP framework versions.
If you have any solutions since the problem occurred, I would like to share it with others. (Or fix the problem if there is any.)

**Comment by prampec** [comment]
There was some stability issues fixed with v3.0.0 . All what we can hope is that is also fixes these problems. :)
