### ISSUE TITLE
Change Button Option

### ISSUE THREAD

**Issue by fabltd** [prampec/IotWebConf#65]
Hi 

Any way to have the portal on startup only load if the button is pressed?

Thanks

J

**Comment by MichGraf** [comment]
Try „iotWebConf.skipApStartup();“ before init.
Attention: the Update-Server does not work in this case. See my following issue.

**Comment by bedawi** [comment]
I also had the problem that the access point mode with captive portal was loaded every time at reboot - even with a configured WiFi connection. I figured out that I had missed to configure the pin as Input. Not all examples have this line and therefore its easy to miss:

```
pinMode(CONFIG_PIN, INPUT_PULLUP);
```

You can, for example, set this up in the setup() function together with skipApStartup():

```
pinMode(CONFIG_PIN, INPUT_PULLUP);
iotWebConf.setConfigPin(CONFIG_PIN);
iotWebConf.skipApStartup();
```
