### ISSUE TITLE
Signal strength

### ISSUE THREAD

**Issue by feder-ico** [prampec/IotWebConf#66]
Hi,
Is there any way to get the signal strength of the current wifi connection?

If I do:
`long rssi = MyConn.RSSI();`
do I get it?

Thanks a lot and regards.

**Comment by tstanescu1** [comment]
Hi Feder, I was able to get the RSSI by using the following example:
int  rssi = WiFi.RSSI();  // eg. -63

**Comment by feder-ico** [comment]
Yes, I did the same. 
Thanks and regards.
