### ISSUE TITLE
Only connects 1 out of 20 times

### ISSUE THREAD

**Issue by fabltd** [prampec/IotWebConf#67]
Hi

Connectivity is very intermittent.  Using a different lib can get 100 % connectivity. Any suggestions. Board is an Adafruit Feather ESP 32.

J

**Comment by feder-ico** [comment]
same problem with ESP12f

**Comment by prampec** [comment]
I personally did not use yield at all, as I like to keep the loop as short as possible. (See my SoftTimer library for details ;) ). And I do not have any experience on yield frequency as well. Sorry!
