### ISSUE TITLE
IotWebConf.delay breaks on ESP32

### ISSUE THREAD

**Issue by MichGraf** [prampec/IotWebConf#70]
I‘ve read that a delay(1) does not work at the ESP32. It restarts.
A change in the .cpp file from  delay(1) to delayMicroseconds(1000) works fine.

**Comment by prampec** [comment]
Do you know the reason why delayMicroseconds() works and delay() don't? Probably again because of that stupid yield().
(I personally do not use the lib on ESP32 for daily basis.)

**Comment by MichGraf** [comment]
Hi

Look at this Board:

https://github.com/espressif/arduino-esp32/issues/903

Regards 
Michael

**Comment by prampec** [comment]
Thank you for referencing that. Okay I will fix it some days, if it also works with ESP8266.

**Comment by 1heinz** [comment]
I can confirm, that on esp32 almost all connections to a wifi network are given up.
With the delayMicroseconds(1000) instead of delay(1) all connections work instantly.
Why not use ?

```
#ifdef ESP8266
delay(1)
#else
delayMicroseconds(1000)
#endif
```

**Comment by prampec** [comment]
Fixed.
