### ISSUE TITLE
Startup device in Station mode if configuration is present in eeprom

### ISSUE THREAD

**Issue by hizzawaseem** [prampec/IotWebConf#76]
Hi,
I am relatively new at firmware development. In my project I want the device to start up in Station mode (instead of AP Mode) if device startup configurations are present in EEPROM. At the current instance the device always starts up in AP mode.
I tried to forcefully switch the device to station mode using these commands but it didn't work.
WiFi.softAPdisconnect(true);
WiFi.mode(WIFI_STA);
Thanks!

**Comment by prampec** [comment]
I think the skipApStartup() is what you are looking for.
