### ISSUE TITLE
Carriage return in serial monitor for debug

### ISSUE THREAD

**Issue by pfeno** [prampec/IotWebConf#77]
Hello all,
In 
https://github.com/prampec/IotWebConf/blob/f94f61326ba463bd340247064a772dc0cc49c653/src/IotWebConf.cpp#L286   replace `Serial.print` by `Serial.println` ;

![image](https://user-images.githubusercontent.com/9256659/66483002-7893d080-eaa4-11e9-9cad-c8c11f94a818.png)

In debug mod, the serial output was better !

**Comment by prampec** [comment]
Thanks!
(Would be great to provide me a pull request.)

**Comment by 1heinz** [comment]
I just made a pull request which fixes this ... and one more thing in the debug output ;-)
