### ISSUE TITLE
ESP32 dependancy 

### ISSUE THREAD

**Issue by pfeno** [prampec/IotWebConf#80]
Hi,

Why you don't remove any dependency on EEPROM for ESP32 ?
Why not use Preference instead ?

Best regards

**Comment by SymbolCsaba** [comment]
It can be hard to build #defines to the whole project. Isn't it?

**Comment by prampec** [comment]
Can you please explain what the problem is with EEPROM? (Also note, that the same code is used for ESP32 and ESP8266!)

**Comment by pfeno** [comment]
-
