### ISSUE TITLE
Can't access portal when the wifi is set wrong

### ISSUE THREAD

**Issue by Tagtwim912** [prampec/IotWebConf#85]
I've got an error when the connection to the Wifi failed (in state 3) and can't even reaccess to the portal (in mode 2)
```
ets Jan  8 2013,rst cause:4, boot mode:(3,6)
wdt reset
load 0x4010f000, len 1384, room 16 
tail 8
chksum 0x2d
csum 0x2d
v8b899c12
~ld
```
Do you have any idea on how to fix it?

**Comment by prampec** [comment]
Do we have any further information in this topic?
