### ISSUE TITLE
Examples of how to retrieve custom parameters

### ISSUE THREAD

**Issue by crumbliness** [prampec/IotWebConf#86]
Are there any examples of how to retrieve/get custom string parameters. I am unable to figure it out from the examples provided. I have the custom parameter example working and merged with an existing sketch.

**Comment by feder-ico** [comment]
What do you mean with retrieve/get parameters?

With this as an example:
`IotWebConfParameter stringParam = IotWebConfParameter("String param", "stringParam", stringParamValue, STRING_LEN);`

you can use stringParamValue as char. For instance, you can do: `serial.print ((String) stringParamValue);` 

Is that what you need?

If you change the value of that variable and you want it to be persistant you will need to do `iotWebConf.configSave();` to save the value on EEPROM but bear in mind that configSave() will make the board to reboot.

Hope this helps.

**Comment by crumbliness** [comment]
OK thanks, - that works. My problem then is how I am using the
stringParamValue(s) in an http: string. . I have a "invalid operands of
types 'const char*' and 'const char [26]' to binary 'operator+'" error.
 I'll need to study some more and try to sort that out.

Thanks again.
