### ISSUE TITLE
wifi SSID value 

### ISSUE THREAD

**Issue by LazzaWA** [prampec/IotWebConf#88]
Hi There, this is not really a issue more a question please. As i'm still in the programming learning phase can you please advise 

I want to skip some of my setup() code if WIFI is not connected. therefore i was wondering how can i check if WIFI SSID has been set ? not sure where to find that variable. i'm thinking i can the do something like 

If (SSID length is > 0) { 
then continue with WIFI related setup() code, like connect to MQTT and run rest of my code etc
 }
else {
continue in AP mode 
}  

cheers

**Comment by prampec** [comment]
You are asking the wrong question. If you want to make decision, whether the SSID is already set, then you can do it with the following term:
  (iotWebConf.getWifiSsidParameter()->valueBuffer[0] != '\0')

But from the code you provided, I believe you need to make decision whether the thing is connected to the WiFi. This can be caught by by setting up a callback like this:
  iotWebConf.setWifiConnectionCallback(&wifiConnected);

Consult with example IotWebConf06MqttApp !
