### ISSUE TITLE
How can I specify the SSID and Password that I want to connect to?

### ISSUE THREAD

**Issue by simpat1zq** [prampec/IotWebConf#89]
I want to hardcode the SSID and Password into the sketch and not have to use the AP. How do I do that? I connected to Wifi the regular way without the library, confirmed it's connected, and then used skipApStartup(), but then I get this error message saying: "SkipApStartup is requested, but either no WiFi was set up, or configButton was pressed" . 

I tried it without the configButton set, and then again with it set to D2 and again set to D3. It still does the same thing. I just want to be able to use this web config parts of this library without having to go through the WiFi setup. Is this possible?

**Comment by prampec** [comment]
I'm not sure, that IotWebConf is the right way for you if you want to hardcode passwords. That is totally against the philosophy of IotWebConf.
(But you can by accessing the internal parameters directly.)
