### ISSUE TITLE
OTA intergration

### ISSUE THREAD

**Issue by LazzaWA** [prampec/IotWebConf#92]
Do you have a sketch that does OTA updates that also blends into the IoTWebConf library  ? If not that would be a good future feature request. 
I'm currently trying to merge the SecureWebUpdater into my sketch but cant get the two sketches to work with each other yet

cheers

**Comment by prampec** [comment]
IotWebConf incorporates ESP8266HTTPUpdateServer. Please consult  	IotWebConf04UpdateServer example!

**Comment by LazzaWA** [comment]
Wow, that was embarrassing. Sorry i should of opened my eyes more. I was trying to understand your cpp file and all sorts. Next time i'll start at the basics :) 

Thanks
