### ISSUE TITLE
clarify web form / remove hardcoded strings

### ISSUE THREAD

**Issue by ThomasWaldmann** [prampec/IotWebConf#98]
```
  this->_thingNameParameter = IotWebConfParameter("Thing name", "iwcThingName", this->_thingName, IOTWEBCONF_WORD_LEN);
  this->_apPasswordParameter = IotWebConfParameter("AP password", "iwcApPassword", this->_apPassword, IOTWEBCONF_WORD_LEN, "password");
  this->_wifiSsidParameter = IotWebConfParameter("WiFi SSID", "iwcWifiSsid", this->_wifiSsid, IOTWEBCONF_WORD_LEN);
  this->_wifiPasswordParameter = IotWebConfParameter("WiFi password", "iwcWifiPassword", this->_wifiPassword, IOTWEBCONF_WORD_LEN, "password");
```

Problematic (because hardcoded) and having confusing strings:
- "Thing name" (we want to use "Geiger accesspoint SSID")
- "AP password" (we want to use "Geiger accesspoint password")
- "WiFi SSID" (we want to use "WiFi client SSID")
- "WiFi password" (we want to use "WiFi client password")

Reasons:
- we do not want to confuse the users of our ESP32-based Geiger Counter, so we need to be clear about what needs to be entered in that form (**without needing addtl. docs** [who reads docs...])
- "Thing name" is just confusing if what one really wants to know is the ESP32 accesspoint SSID.
- We preferred "Geiger" over "ESP32" because our users know they have a geiger counter, but maybe not that it is based on ESP32 (we have non-technical users).
- If one is talking about the same thing (which is configuring the ESP32 builtin accesspoint here), one should use the same words for it. Not "Thing name" in first field and "AP" in second field. This is also confusing because the user also has his home router, which is also an "AP", so it is totally unclear what is meant.
- We have 2 WiFis here, so we need to be clear when the ESP32 builtin **accesspoint** is meant and when ESP32-based WiFi **client** (and needs the SSID/password to connect) is meant.

So, can we have these strings configurable, please?

**Comment by ThomasWaldmann** [comment]
For a quick hack (just changing the hardcoded strings), this would be already an improvement (clarity):

- "Thing name" --> "WiFi accesspoint SSID"
- "AP password" --> "WiFi accesspoint password"
- "WiFi SSID" --> "WiFi client SSID"
- "WiFi password" --> "WiFi client password"

**Comment by prampec** [comment]
You can access internal parameters directly by e.g. getThingNameParameter() where you can overwrite the 'label' with you designated string.

**Comment by ThomasWaldmann** [comment]
Good hint, I'll try.

But still you could make the defaults more clear, see above.

**Comment by prampec** [comment]
Thing name is also used e.g. in host name. I use the word "WiFi" for station mode only, to keep things clear. I do not believe, that word "client" would help users understanding the situation.

**Comment by ThomasWaldmann** [comment]
There are wifi accesspoints, there are wifi clients, so your usage is a bit specially and non-standard maybe?

And accesspoint vs. client helps at least more than what you have.

But anyway, do what you want and thanks for your hint, it worked. \o/

```
  iotWebConf.getThingNameParameter()->label = "WiFi accesspoint SSID";
  iotWebConf.getApPasswordParameter()->label = "WiFi accesspoint password";
  iotWebConf.getWifiSsidParameter()->label = "WiFi client SSID";
  iotWebConf.getWifiPasswordParameter()->label = "WiFi client password";
```
